{% set name = "pysynphot" %}
{% set version = "2.0.0" %}
{% set sha256 = "45c29f69248ec8a641c38625d11409dd2411ea1d6faffd8c3b44da354c4d22e7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 5
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37 or win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - astropy
    - {{ pin_compatible('numpy') }}
    - beautifulsoup4
    - six
    - setuptools

test:
  imports:
    - pysynphot

about:
  home: https://github.com/spacetelescope/pysynphot
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Synthetic photometry package from Astrolib.
  doc_url: https://pysynphot.readthedocs.io
  dev_url: https://github.com/spacetelescope/pysynphot

extra:
  recipe-maintainers:
    - mfisherlevine
    - pllim
